const constants = {
    SET_FIRST_COLOR: "SET_FIRST_COLOR",
    SET_SECOND_COLOR: "SET_SECOND_COLOR",
    SET_COLOR_DEGREE: "SET_COLOR_DEGREE",
    SET_FONT_SIZE: "SET_FONT_SIZE",
    SET_FONT_COLOR: "SET_FONT_COLOR",
    SET_FONT_FAMILY: "SET_FONT_FAMILY",
    SET_TYPING: " SET_TYPING",
    CLEAR_TYPING: "CLEAR_TYPING",
    RESET: "RESET",
    SAVE_DESIGN: "SAVE_DESIGN"
}

export default constants;